// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CheckboxController from "./checkbox_controller"
application.register("checkbox", CheckboxController)

import ClassController from "./class_controller"
application.register("class", ClassController)

import CollapseDeleteController from "./collapse_delete_controller"
application.register("collapse-delete", CollapseDeleteController)

import CollapseHoursController from "./collapse_hours_controller"
application.register("collapse-hours", CollapseHoursController)

import ComboboxContentController from "./combobox_content_controller"
application.register("combobox-content", ComboboxContentController)

import ComboboxController from "./combobox_controller"
application.register("combobox", ComboboxController)

import ComboboxItemController from "./combobox_item_controller"
application.register("combobox-item", ComboboxItemController)

import ComboboxSelectedItemsController from "./combobox_selected_items_controller"
application.register("combobox-selected-items", ComboboxSelectedItemsController)

import CookieConsentController from "./cookie_consent_controller"
application.register("cookie-consent", CookieConsentController)

import CustomDialogController from "./custom_dialog_controller"
application.register("custom-dialog", CustomDialogController)

import CustomDisableController from "./custom_disable_controller"
application.register("custom-disable", CustomDisableController)

import CustomDropdownController from "./custom_dropdown_controller"
application.register("custom-dropdown", CustomDropdownController)

import CustomInputController from "./custom_input_controller"
application.register("custom-input", CustomInputController)

import DynamicTaskUrlController from "./dynamic_task_url_controller"
application.register("dynamic-task-url", DynamicTaskUrlController)

import FileUploadController from "./file_upload_controller"
application.register("file-upload", FileUploadController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import FormController from "./form_controller"
application.register("form", FormController)

import GroupedSelectMultipleController from "./grouped_select_multiple_controller"
application.register("grouped-select-multiple", GroupedSelectMultipleController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InviteUsersController from "./invite_users_controller"
application.register("invite-users", InviteUsersController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import PrintController from "./print_controller"
application.register("print", PrintController)

import RefreshMinutesController from "./refresh_minutes_controller"
application.register("refresh-minutes", RefreshMinutesController)

import ReportEditController from "./report_edit_controller"
application.register("report-edit", ReportEditController)

import RubyUi__DialogController from "./ruby_ui/dialog_controller"
application.register("ruby-ui--dialog", RubyUi__DialogController)

import RubyUi__FormFieldController from "./ruby_ui/form_field_controller"
application.register("ruby-ui--form-field", RubyUi__FormFieldController)

import RubyUi__PopoverController from "./ruby_ui/popover_controller"
application.register("ruby-ui--popover", RubyUi__PopoverController)

import SelectMultipleController from "./select_multiple_controller"
application.register("select-multiple", SelectMultipleController)

import ShowOnValueController from "./show_on_value_controller"
application.register("show-on-value", ShowOnValueController)

import SliderTabsController from "./slider_tabs_controller"
application.register("slider-tabs", SliderTabsController)

import SnackbarController from "./snackbar_controller"
application.register("snackbar", SnackbarController)

import TimeTasksController from "./time_tasks_controller"
application.register("time-tasks", TimeTasksController)

import VisibilityController from "./visibility_controller"
application.register("visibility", VisibilityController)
