// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CheckboxController from "./checkbox_controller"
application.register("checkbox", CheckboxController)

import ClassController from "./class_controller"
application.register("class", ClassController)

import CollapseDeleteController from "./collapse_delete_controller"
application.register("collapse-delete", CollapseDeleteController)

import CollapseHoursController from "./collapse_hours_controller"
application.register("collapse-hours", CollapseHoursController)

import FormController from "./form_controller"
application.register("form", FormController)

import GroupedSelectMultipleController from "./grouped_select_multiple_controller"
application.register("grouped-select-multiple", GroupedSelectMultipleController)

import SelectMultipleController from "./select_multiple_controller"
application.register("select-multiple", SelectMultipleController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import CustomInputController from "./custom_input_controller"
application.register("custom-input", CustomInputController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import RefreshMinutesController from "./refresh_minutes_controller"
application.register("refresh-minutes", RefreshMinutesController)

import ReportEditController from "./report_edit_controller"
application.register("report-edit", ReportEditController)

import TimeTasksController from "./time_tasks_controller"
application.register("time-tasks", TimeTasksController)

import VisibilityController from "./visibility_controller"
application.register("visibility", VisibilityController)

import DialogController from "./custom_dialog_controller";
application.register("custom-dialog", DialogController);

import SnackbarController from "./snackbar_controller";
application.register("snackbar", SnackbarController);

import CustomDropdownController from "./custom_dropdown_controller";
application.register("custom-dropdown", CustomDropdownController);

import PrintController from "./print_controller";
application.register("print", PrintController);

import FileUploadController from "./file_upload_controller";
application.register("file-upload", FileUploadController);

import CustomDisableController from "./custom_disable_controller";
application.register("custom-disable", CustomDisableController);

import ShowOnValueController from './show_on_value_controller';
application.register("show-on-value", ShowOnValueController);

import DynamicTaskUrlController from './dynamic_task_url_controller';
application.register("dynamic-task-url", DynamicTaskUrlController);

import InviteUsersController from './invite_users_controller';
application.register("invite-users", InviteUsersController);

import FlatpickrController from './flatpickr_controller';
document.addEventListener('turbo:load', () => {
  application.register("flatpickr", FlatpickrController);
});

import SliderTabsController from "./slider_tabs_controller";
application.register("slider-tabs", SliderTabsController);


// TODO: fetch controllers from app/javascript/controllers/**/*_controller.js and load/register everything automatically, the filename of the controller will then be used as the controller identifier in the DOM
