shared:
  from: "noreply@stemplin.com"
  templates:
    user:
      welcome:
        # Same template (english) for both languages. TODO: fix
        nb:
          template_id: "d-f78bbd2312eb4e62904e90813cddfde9"
        en:
          template_id: "d-f78bbd2312eb4e62904e90813cddfde9"
      project_invitation:
        nb:
          template_id: "d-660209244f7e464e9ac4eed8f670e73d"
        en:
          template_id: "d-660209244f7e464e9ac4eed8f670e73d"
      password_reset:
        nb:
          template_id: "d-7738fd5757d5497ca4973e572ba4b26e"
        en:
          template_id: "d-7738fd5757d5497ca4973e572ba4b26e"
