shared:
  from: "noreply@stemplin.com"
  templates:
    user:
      welcome:
        nb:
          template_id: <%= ENV["WELCOME_NB_TEMPLATE_ID"] %>
        en:
          template_id: <%= ENV["WELCOME_EN_TEMPLATE_ID"] %>
      password_reset:
        nb:
          template_id: <%= ENV["PASSWORD_RESET_NB_TEMPLATE_ID"] %>
        en:
          template_id: <%= ENV["PASSWORD_RESET_EN_TEMPLATE_ID"] %>
      project_invitation:
        nb:
          template_id: <%= ENV["PROJECT_INVITATION_NB_TEMPLATE_ID"] %>
        en:
          template_id: <%= ENV["PROJECT_INVITATION_EN_TEMPLATE_ID"] %>
