shared:
  from: "noreply@stemplin.com"
  templates:
    user:
      welcome:
        # Same template (english) for both languages. TODO: fix
        nb:
          template_id: "d-313b9d8d45b642cdb0ab07922c6b6096"
        en:
          template_id: "d-313b9d8d45b642cdb0ab07922c6b6096"
      password_reset:
        nb:
          template_id: "d-b7fd90a827e34d0b8cd837ed8afaaf60"
        en:
          template_id: "d-b7fd90a827e34d0b8cd837ed8afaaf60"
      project_invitation:
        nb:
          template_id: "d-660209244f7e464e9ac4eed8f670e73d"
        en:
          template_id: "d-660209244f7e464e9ac4eed8f670e73d"
